#!/bin/bash
# git pre-commit hook to detect PEP8 problems
/home/caribou/git/pep8-git-hook/pre-commit
typeset -i ret=$?
# If there are whitespace errors, print the offending file names and fail.
if (( $ret != 0 )) && [[ -f .git/refs/heads/master ]];then
	exec git diff-index --check --cached HEAD --
fi
